ALTER TABLE users ADD COLUMN IF NOT EXISTS twitch_username VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS youtube_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS x_username VARCHAR(50);
