ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS accent_color VARCHAR(7) DEFAULT '#4f8cff';
ALTER TABLE users ADD COLUMN IF NOT EXISTS pronouns VARCHAR(40);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS favorite_game VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_style VARCHAR(20) DEFAULT 'default';
